###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID vlsi)
#  Generated on:      Mon Dec  4 01:12:31 2017
#  Design:            fft8
#  Command:           saveDesign fft8_03_prects.enc
###############################################################
current_design fft8
create_clock [get_ports {clk}]  -name clk -period 40.000000 -waveform {0.000000 20.000000}
