###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID vlsi)
#  Generated on:      Fri Nov 10 14:47:58 2017
#  Design:            myPMul32_4
#  Command:           saveDesign myPMul32_4
###############################################################
current_design myPMul32_4
create_clock [get_ports {g_inClk}]  -name myCLK -period 6.400000 -waveform {0.000000 3.200000}
